import React, { useState, useEffect } from 'react';
import {
  CreateTeacherDTO,
  TeacherGender,
  TeacherStatus,
  EmploymentType,
  TeacherClassRole,
} from '../../types/teacher';
import { Modal } from '../common/Modal';
import { Button } from '../common/Button';
import { useTeachers } from '../../context/TeacherContext';
import { useBranch } from '../../context/BranchContext';
import { useAcademic } from '../../context/AcademicContext';
import { useAuth } from '../../context/AuthContext';
import {
  User,
  GraduationCap,
  Building2,
  Calendar,
  Phone,
  Mail,
  MapPin,
  Shield,
  BookOpen,
  School,
  DollarSign,
  AlertCircle,
  CheckCircle2,
  Info,
} from 'lucide-react';

interface TeacherRegistrationModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess?: () => void;
}

export const TeacherRegistrationModal: React.FC<TeacherRegistrationModalProps> = ({
  isOpen,
  onClose,
  onSuccess,
}) => {
  const { createTeacher, generateNextNumber } = useTeachers();
  const { branches, accessibleBranches, activeBranchId } = useBranch();
  const { subjects, classes, years } = useAcademic();
  const { currentUser, isSuperAdmin } = useAuth();

  const availableBranches = isSuperAdmin ? branches : accessibleBranches;

  const defaultBranch =
    activeBranchId && activeBranchId !== 'all'
      ? activeBranchId
      : availableBranches[0]?.id || '';

  // Form State
  const [selectedBranchId, setSelectedBranchId] = useState<string>(defaultBranch);
  const [teacherNumber, setTeacherNumber] = useState<string>('');
  const [autoGeneratedNumber, setAutoGeneratedNumber] = useState<string>('');
  const [isCustomNumber, setIsCustomNumber] = useState<boolean>(false);

  // Identity & Names
  const [firstNameAr, setFirstNameAr] = useState('');
  const [middleNameAr, setMiddleNameAr] = useState('');
  const [lastNameAr, setLastNameAr] = useState('');
  const [firstNameEn, setFirstNameEn] = useState('');
  const [middleNameEn, setMiddleNameEn] = useState('');
  const [lastNameEn, setLastNameEn] = useState('');
  const [gender, setGender] = useState<TeacherGender>('male');
  const [dateOfBirth, setDateOfBirth] = useState('');
  const [nationality, setNationality] = useState('سعودي');
  const [nationalId, setNationalId] = useState('');
  const [passportNumber, setPassportNumber] = useState('');

  // Contact
  const [phoneNumber, setPhoneNumber] = useState('');
  const [alternatePhoneNumber, setAlternatePhoneNumber] = useState('');
  const [email, setEmail] = useState('');
  const [address, setAddress] = useState('');

  // Employment
  const [hireDate, setHireDate] = useState(new Date().toISOString().split('T')[0]);
  const [employmentType, setEmploymentType] = useState<EmploymentType>('FULL_TIME');
  const [employmentStatus, setEmploymentStatus] = useState<TeacherStatus>('ACTIVE');
  const [specialization, setSpecialization] = useState('');
  const [perLessonRate, setPerLessonRate] = useState<number | undefined>(undefined);
  const [notes, setNotes] = useState('');

  // Initial Qualification (Optional)
  const [qualDegree, setQualDegree] = useState('');
  const [qualField, setQualField] = useState('');
  const [qualInstitution, setQualInstitution] = useState('');
  const [qualYear, setQualYear] = useState<number>(new Date().getFullYear());

  // Initial Subject Assignments
  const [selectedSubjectIds, setSelectedSubjectIds] = useState<string[]>([]);

  // Initial Class Assignment
  const [selectedClassId, setSelectedClassId] = useState<string>('');
  const [selectedClassRole, setSelectedClassRole] = useState<TeacherClassRole>('PRIMARY_TEACHER');

  // Submission State
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  // Update auto-generated teacher number whenever branch changes
  useEffect(() => {
    if (selectedBranchId) {
      try {
        const nextNum = generateNextNumber(selectedBranchId);
        setAutoGeneratedNumber(nextNum);
        if (!isCustomNumber) {
          setTeacherNumber(nextNum);
        }
      } catch {
        // Fallback
        const fallback = `TCH-${new Date().getFullYear()}-001`;
        setAutoGeneratedNumber(fallback);
        if (!isCustomNumber) setTeacherNumber(fallback);
      }
    }
  }, [selectedBranchId, generateNextNumber, isCustomNumber]);

  // Reset selected subjects/classes if branch changes to prevent cross-branch leaks
  useEffect(() => {
    setSelectedSubjectIds([]);
    setSelectedClassId('');
  }, [selectedBranchId]);

  // Filter available subjects and classes strictly for selected branch
  const branchSubjects = subjects.filter((s) => s.branchId === selectedBranchId && s.status === 'active');
  const branchClasses = classes.filter((c) => c.branchId === selectedBranchId && c.status === 'active');
  const branchYears = years.filter((y) => y.branchId === selectedBranchId && y.status === 'ACTIVE');
  const activeYear = branchYears.find((y) => y.isCurrent) || branchYears[0];

  const handleToggleSubject = (subjectId: string) => {
    setSelectedSubjectIds((prev) =>
      prev.includes(subjectId) ? prev.filter((id) => id !== subjectId) : [...prev, subjectId]
    );
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMessage(null);

    // Validation
    if (!firstNameAr.trim() || !lastNameAr.trim()) {
      setErrorMessage('الاسم الأول واسم العائلة باللغة العربية مطلوبان.');
      return;
    }
    if (!firstNameEn.trim() || !lastNameEn.trim()) {
      setErrorMessage('الاسم الأول واسم العائلة باللغة الإنجليزية مطلوبان.');
      return;
    }
    if (!phoneNumber.trim()) {
      setErrorMessage('رقم الجوال الأساسي مطلوب.');
      return;
    }
    if (!specialization.trim()) {
      setErrorMessage('التخصص الأكاديمي الرئيسي للمعلم مطلوب.');
      return;
    }

    try {
      setIsSubmitting(true);

      const qualificationsPayload = qualDegree.trim()
        ? [
            {
              degree: qualDegree.trim(),
              fieldOfStudy: qualField.trim() || specialization.trim(),
              institution: qualInstitution.trim(),
              graduationYear: qualYear,
              isHighestDegree: true,
            },
          ]
        : undefined;

      const classAssignmentsPayload =
        selectedClassId && activeYear
          ? [
              {
                classId: selectedClassId,
                academicYearId: activeYear.id,
                role: selectedClassRole,
              },
            ]
          : undefined;

      const dto: CreateTeacherDTO = {
        branchId: selectedBranchId,
        teacherNumber: isCustomNumber && teacherNumber.trim() ? teacherNumber.trim() : undefined,
        firstNameAr: firstNameAr.trim(),
        middleNameAr: middleNameAr.trim() || undefined,
        lastNameAr: lastNameAr.trim(),
        firstNameEn: firstNameEn.trim(),
        middleNameEn: middleNameEn.trim() || undefined,
        lastNameEn: lastNameEn.trim(),
        gender,
        dateOfBirth: dateOfBirth || undefined,
        nationality: nationality.trim() || undefined,
        nationalId: nationalId.trim() || undefined,
        passportNumber: passportNumber.trim() || undefined,
        phoneNumber: phoneNumber.trim(),
        alternatePhoneNumber: alternatePhoneNumber.trim() || undefined,
        email: email.trim().toLowerCase() || undefined,
        address: address.trim() || undefined,
        hireDate: hireDate || undefined,
        employmentStatus,
        employmentType,
        specialization: specialization.trim(),
        perLessonRate: employmentType === 'TEMPORARY' ? perLessonRate : undefined,
        notes: notes.trim() || undefined,
        qualifications: qualificationsPayload,
        subjectIds: selectedSubjectIds.length > 0 ? selectedSubjectIds : undefined,
        classAssignments: classAssignmentsPayload,
      };

      await createTeacher(dto);
      if (onSuccess) onSuccess();
      onClose();
    } catch (err: any) {
      setErrorMessage(err.message || 'فشل في تسجيل المعلم.');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      maxWidth="2xl"
      title={
        <div className="flex items-center gap-2.5">
          <div className="w-9 h-9 rounded-xl bg-blue-100 dark:bg-blue-900/40 text-blue-600 dark:text-blue-400 flex items-center justify-center font-bold">
            <User className="w-5 h-5" />
          </div>
          <div>
            <div className="text-base sm:text-lg font-bold text-slate-900 dark:text-slate-100">
              تسجيل معلم جديد بالفرع
            </div>
            <div className="text-xs text-slate-500 dark:text-slate-400">
              إضافة كادر تعليمي جديد، تحديد التخصص الأكاديمي، المواد المسندة وتسكين الفصول
            </div>
          </div>
        </div>
      }
    >
      <form onSubmit={handleSubmit} className="space-y-4">
        {errorMessage && (
          <div className="p-3 rounded-xl bg-rose-50 dark:bg-rose-950/40 border border-rose-200 dark:border-rose-800 text-xs text-rose-700 dark:text-rose-300 flex items-center gap-2">
            <AlertCircle className="w-4 h-4 shrink-0 text-rose-500" />
            <span>{errorMessage}</span>
          </div>
        )}

        {/* 1. Branch Selection & Identifier */}
        <div className="p-3.5 rounded-xl bg-blue-50/50 dark:bg-blue-950/30 border border-blue-200/80 dark:border-blue-900/60 space-y-3">
          <span className="text-[11px] font-bold uppercase tracking-wider text-blue-700 dark:text-blue-300 flex items-center gap-1.5">
            <Building2 className="w-3.5 h-3.5" />
            الفرع والرقم الوظيفي للمعلم
          </span>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
            <div>
              <label className="block text-[11px] font-semibold text-slate-700 dark:text-slate-300 mb-1">
                الفرع المدرسي التابع له *
              </label>
              <select
                value={selectedBranchId}
                onChange={(e) => setSelectedBranchId(e.target.value)}
                className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs font-medium cursor-pointer"
              >
                {availableBranches.map((b) => (
                  <option key={b.id} value={b.id}>
                    {b.nameAr} ({b.city})
                  </option>
                ))}
              </select>
            </div>
            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="text-[11px] font-semibold text-slate-700 dark:text-slate-300">
                  الرقم الوظيفي التعريفي *
                </label>
                <button
                  type="button"
                  onClick={() => setIsCustomNumber(!isCustomNumber)}
                  className="text-[10px] text-blue-600 dark:text-blue-400 hover:underline cursor-pointer"
                >
                  {isCustomNumber ? 'توليد تلقائي' : 'رقم مخصص'}
                </button>
              </div>
              <input
                type="text"
                value={teacherNumber}
                onChange={(e) => setTeacherNumber(e.target.value)}
                disabled={!isCustomNumber}
                placeholder={autoGeneratedNumber}
                className="w-full px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs font-mono font-bold text-blue-700 dark:text-blue-400 disabled:opacity-80"
              />
            </div>
          </div>
        </div>

        {/* 2. Names (Arabic & English) */}
        <div className="space-y-2.5">
          <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500">
            الاسم الكامل (عربي وإنجليزي)
          </span>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 text-xs">
            <div>
              <label className="block text-[11px] font-medium text-slate-600 dark:text-slate-300 mb-1">
                الاسم الأول (بالعربية) *
              </label>
              <input
                type="text"
                required
                placeholder="مثال: فهد"
                value={firstNameAr}
                onChange={(e) => setFirstNameAr(e.target.value)}
                className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs"
              />
            </div>
            <div>
              <label className="block text-[11px] font-medium text-slate-600 dark:text-slate-300 mb-1">
                اسم الأب / الأوسط
              </label>
              <input
                type="text"
                placeholder="مثال: عبدالعزيز"
                value={middleNameAr}
                onChange={(e) => setMiddleNameAr(e.target.value)}
                className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs"
              />
            </div>
            <div>
              <label className="block text-[11px] font-medium text-slate-600 dark:text-slate-300 mb-1">
                اسم العائلة (بالعربية) *
              </label>
              <input
                type="text"
                required
                placeholder="مثال: المنصور"
                value={lastNameAr}
                onChange={(e) => setLastNameAr(e.target.value)}
                className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs"
              />
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 text-xs">
            <div>
              <label className="block text-[11px] font-medium text-slate-600 dark:text-slate-300 mb-1">
                First Name (EN) *
              </label>
              <input
                type="text"
                required
                placeholder="e.g. Fahad"
                value={firstNameEn}
                onChange={(e) => setFirstNameEn(e.target.value)}
                className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs"
              />
            </div>
            <div>
              <label className="block text-[11px] font-medium text-slate-600 dark:text-slate-300 mb-1">
                Middle Name (EN)
              </label>
              <input
                type="text"
                placeholder="e.g. Abdulaziz"
                value={middleNameEn}
                onChange={(e) => setMiddleNameEn(e.target.value)}
                className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs"
              />
            </div>
            <div>
              <label className="block text-[11px] font-medium text-slate-600 dark:text-slate-300 mb-1">
                Last Name (EN) *
              </label>
              <input
                type="text"
                required
                placeholder="e.g. Al-Mansoor"
                value={lastNameEn}
                onChange={(e) => setLastNameEn(e.target.value)}
                className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs"
              />
            </div>
          </div>
        </div>

        {/* 3. Gender, DOB, Nationality, National ID */}
        <div className="grid grid-cols-1 sm:grid-cols-4 gap-2.5 text-xs">
          <div>
            <label className="block text-[11px] font-medium text-slate-600 dark:text-slate-300 mb-1">
              الجنس *
            </label>
            <select
              value={gender}
              onChange={(e) => setGender(e.target.value as TeacherGender)}
              className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs cursor-pointer"
            >
              <option value="male">ذكر</option>
              <option value="female">أنثى</option>
            </select>
          </div>
          <div>
            <label className="block text-[11px] font-medium text-slate-600 dark:text-slate-300 mb-1">
              تاريخ الميلاد
            </label>
            <input
              type="date"
              value={dateOfBirth}
              onChange={(e) => setDateOfBirth(e.target.value)}
              className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs"
            />
          </div>
          <div>
            <label className="block text-[11px] font-medium text-slate-600 dark:text-slate-300 mb-1">
              الجنسية
            </label>
            <input
              type="text"
              value={nationality}
              onChange={(e) => setNationality(e.target.value)}
              placeholder="سعودي"
              className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs"
            />
          </div>
          <div>
            <label className="block text-[11px] font-medium text-slate-600 dark:text-slate-300 mb-1">
              الهوية الوطنية / الإقامة
            </label>
            <input
              type="text"
              value={nationalId}
              onChange={(e) => setNationalId(e.target.value)}
              placeholder="10XXXXXXXX"
              className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs font-mono"
            />
          </div>
        </div>

        {/* 4. Contact Information */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 text-xs">
          <div>
            <label className="block text-[11px] font-medium text-slate-600 dark:text-slate-300 mb-1">
              رقم الجوال الأساسي *
            </label>
            <input
              type="tel"
              required
              value={phoneNumber}
              onChange={(e) => setPhoneNumber(e.target.value)}
              placeholder="+9665XXXXXXXX"
              className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs font-mono dir-ltr text-right"
            />
          </div>
          <div>
            <label className="block text-[11px] font-medium text-slate-600 dark:text-slate-300 mb-1">
              رقم جوال بديل
            </label>
            <input
              type="tel"
              value={alternatePhoneNumber}
              onChange={(e) => setAlternatePhoneNumber(e.target.value)}
              placeholder="+9665XXXXXXXX"
              className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs font-mono dir-ltr text-right"
            />
          </div>
          <div>
            <label className="block text-[11px] font-medium text-slate-600 dark:text-slate-300 mb-1">
              البريد الإلكتروني
            </label>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="teacher@schoolms.edu"
              className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs font-mono"
            />
          </div>
        </div>

        {/* 5. Professional & Employment Details */}
        <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-800 space-y-3">
          <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
            البيانات المهنية والتخصص
          </span>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 text-xs">
            <div>
              <label className="block text-[11px] font-medium text-slate-700 dark:text-slate-300 mb-1">
                التخصص الأكاديمي الرئيسي *
              </label>
              <input
                type="text"
                required
                value={specialization}
                onChange={(e) => setSpecialization(e.target.value)}
                placeholder="مثال: الرياضيات والفيزياء"
                className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs"
              />
            </div>
            <div>
              <label className="block text-[11px] font-medium text-slate-700 dark:text-slate-300 mb-1">
                نوع التعاقد الوظيفي *
              </label>
              <select
                value={employmentType}
                onChange={(e) => setEmploymentType(e.target.value as EmploymentType)}
                className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs cursor-pointer"
              >
                <option value="FULL_TIME">دوام كامل (رسمي)</option>
                <option value="PART_TIME">دوام جزئي</option>
                <option value="CONTRACT">عقد سنوي محدد</option>
                <option value="TEMPORARY">معلم حصص (مؤقت / بالأجر)</option>
              </select>
            </div>
            <div>
              <label className="block text-[11px] font-medium text-slate-700 dark:text-slate-300 mb-1">
                تاريخ التعيين والالتحاق
              </label>
              <input
                type="date"
                value={hireDate}
                onChange={(e) => setHireDate(e.target.value)}
                className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs"
              />
            </div>
          </div>

          {employmentType === 'TEMPORARY' && (
            <div className="p-2.5 rounded-lg bg-blue-50 dark:bg-blue-950/40 border border-blue-200 dark:border-blue-900 flex items-center gap-3 text-xs">
              <DollarSign className="w-4 h-4 text-blue-600" />
              <div className="flex-1">
                <label className="block text-[11px] font-medium text-blue-900 dark:text-blue-200 mb-0.5">
                  أجر الحصة الواحدة (ر.س) للمعلم المؤقت:
                </label>
                <input
                  type="number"
                  min={0}
                  step={5}
                  value={perLessonRate || ''}
                  onChange={(e) => setPerLessonRate(parseFloat(e.target.value) || undefined)}
                  placeholder="مثال: 75"
                  className="w-36 px-2.5 py-1 rounded border border-blue-300 dark:border-blue-800 bg-white dark:bg-slate-900 text-xs"
                />
              </div>
            </div>
          )}
        </div>

        {/* 6. Initial Qualifications (Optional Quick Entry) */}
        <div className="space-y-2">
          <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500">
            أعلى مؤهل أكاديمي (اختياري)
          </span>
          <div className="grid grid-cols-1 sm:grid-cols-4 gap-2 text-xs">
            <div>
              <input
                type="text"
                placeholder="الدرجة (بكالوريوس...)"
                value={qualDegree}
                onChange={(e) => setQualDegree(e.target.value)}
                className="w-full px-2.5 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs"
              />
            </div>
            <div>
              <input
                type="text"
                placeholder="التخصص الدقيق"
                value={qualField}
                onChange={(e) => setQualField(e.target.value)}
                className="w-full px-2.5 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs"
              />
            </div>
            <div>
              <input
                type="text"
                placeholder="الجامعة المانحة"
                value={qualInstitution}
                onChange={(e) => setQualInstitution(e.target.value)}
                className="w-full px-2.5 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs"
              />
            </div>
            <div>
              <input
                type="number"
                placeholder="سنة التخرج"
                min={1970}
                max={new Date().getFullYear()}
                value={qualYear}
                onChange={(e) => setQualYear(parseInt(e.target.value, 10))}
                className="w-full px-2.5 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs"
              />
            </div>
          </div>
        </div>

        {/* 7. Initial Subject Assignments */}
        {branchSubjects.length > 0 && (
          <div className="space-y-2">
            <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500">
              إسناد المواد الدراسية بالفرع ({branchSubjects.length} مادة معتمدة)
            </span>
            <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/40 border border-slate-200 dark:border-slate-800 flex flex-wrap gap-2 max-h-32 overflow-y-auto">
              {branchSubjects.map((s) => {
                const isSelected = selectedSubjectIds.includes(s.id);
                return (
                  <button
                    key={s.id}
                    type="button"
                    onClick={() => handleToggleSubject(s.id)}
                    className={`px-2.5 py-1.5 rounded-lg text-xs font-medium border transition-colors cursor-pointer flex items-center gap-1.5 ${
                      isSelected
                        ? 'bg-blue-50 dark:bg-blue-950/60 border-blue-500 text-blue-700 dark:text-blue-300 font-bold'
                        : 'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 hover:border-slate-300'
                    }`}
                  >
                    <span>{s.nameAr}</span>
                    <span className="text-[10px] text-slate-400 font-mono">({s.subjectCode})</span>
                  </button>
                );
              })}
            </div>
          </div>
        )}

        {/* 8. Initial Class Assignment (Optional) */}
        {branchClasses.length > 0 && (
          <div className="space-y-2">
            <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500">
              تسكين أولي في فصل دراسي (اختياري)
            </span>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
              <select
                value={selectedClassId}
                onChange={(e) => setSelectedClassId(e.target.value)}
                className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs cursor-pointer"
              >
                <option value="">-- بدون تسكين حالياً --</option>
                {branchClasses.map((c) => (
                  <option key={c.id} value={c.id}>
                    {c.nameAr} ({c.nameEn})
                  </option>
                ))}
              </select>
              {selectedClassId && (
                <select
                  value={selectedClassRole}
                  onChange={(e) => setSelectedClassRole(e.target.value as TeacherClassRole)}
                  className="w-full px-3 py-1.5 rounded-lg border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs cursor-pointer"
                >
                  <option value="PRIMARY_TEACHER">معلم أساسي للفصل</option>
                  <option value="HOMEROOM_TEACHER">رائد فصل (Homeroom)</option>
                  <option value="SUBJECT_TEACHER">معلم مادة بالفصل</option>
                  <option value="ASSISTANT_TEACHER">معلم مساعد</option>
                </select>
              )}
            </div>
          </div>
        )}

        {/* Security & Account Distinction Note */}
        <div className="p-3 rounded-xl bg-slate-100 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 text-xs text-slate-600 dark:text-slate-400 flex items-start gap-2">
          <Info className="w-4 h-4 text-blue-500 shrink-0 mt-0.5" />
          <p>
            ملاحظة أمنية: تسجيل المعلم ينشئ سجلاً وظيفياً وأكاديمياً مستقلاً. لن يتم إنشاء حساب دخول للمنصة (Login User) تلقائياً، حفاظاً على العزل الأمني ومصفوفة الصلاحيات.
          </p>
        </div>

        {/* Actions */}
        <div className="flex items-center justify-end gap-2 pt-3 border-t border-slate-200 dark:border-slate-800">
          <Button variant="secondary" size="sm" type="button" onClick={onClose} disabled={isSubmitting}>
            إلغاء
          </Button>
          <Button variant="primary" size="sm" type="submit" disabled={isSubmitting}>
            {isSubmitting ? 'جارٍ تسجيل المعلم...' : 'إتمام تسجيل المعلم'}
          </Button>
        </div>
      </form>
    </Modal>
  );
};
