/**
 * School Management System - Database Architecture Contract
 * Normalized relational schema specification for all 15 phases.
 */

export interface DBSchemaDefinition {
  tableName: string;
  description: string;
  primaryKey: string;
  foreignKeys: Record<string, string>;
  indexes: string[];
  columns: {
    name: string;
    type: string;
    nullable: boolean;
    description: string;
  }[];
}

export const DATABASE_SCHEMA: Record<string, DBSchemaDefinition> = {
  branches: {
    tableName: 'branches',
    description: 'School campuses with independent address, capacity, and operational parameters',
    primaryKey: 'id',
    foreignKeys: { manager_id: 'users.id' },
    indexes: ['code', 'status'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'Unique UUID' },
      { name: 'code', type: 'VARCHAR(16)', nullable: false, description: 'Unique campus code (e.g. RUH-01)' },
      { name: 'name_ar', type: 'VARCHAR(128)', nullable: false, description: 'Arabic campus name' },
      { name: 'name_en', type: 'VARCHAR(128)', nullable: false, description: 'English campus name' },
      { name: 'city', type: 'VARCHAR(64)', nullable: false, description: 'City name' },
      { name: 'address', type: 'TEXT', nullable: false, description: 'Physical address' },
      { name: 'phone', type: 'VARCHAR(32)', nullable: false, description: 'Contact phone' },
      { name: 'email', type: 'VARCHAR(128)', nullable: false, description: 'Campus official email' },
      { name: 'manager_id', type: 'VARCHAR(36)', nullable: true, description: 'Branch manager user reference' },
      { name: 'status', type: 'VARCHAR(16)', nullable: false, description: 'active | inactive' },
      { name: 'created_at', type: 'TIMESTAMP', nullable: false, description: 'Creation timestamp' },
    ],
  },

  users: {
    tableName: 'users',
    description: 'All system actors: Super Admin, Branch Managers, Teachers, Staff, Accountants',
    primaryKey: 'id',
    foreignKeys: { role_id: 'roles.id' },
    indexes: ['email', 'role_id', 'active'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'Unique UUID' },
      { name: 'email', type: 'VARCHAR(128)', nullable: false, description: 'User login email' },
      { name: 'password_hash', type: 'VARCHAR(255)', nullable: false, description: 'Hashed password' },
      { name: 'name_ar', type: 'VARCHAR(128)', nullable: false, description: 'Arabic full name' },
      { name: 'name_en', type: 'VARCHAR(128)', nullable: false, description: 'English full name' },
      { name: 'phone', type: 'VARCHAR(32)', nullable: true, description: 'Contact mobile' },
      { name: 'role_id', type: 'VARCHAR(36)', nullable: false, description: 'Associated role ID' },
      { name: 'active', type: 'BOOLEAN', nullable: false, description: 'Account status' },
      { name: 'avatar_url', type: 'TEXT', nullable: true, description: 'Profile picture' },
      { name: 'created_at', type: 'TIMESTAMP', nullable: false, description: 'Registration date' },
      { name: 'last_login', type: 'TIMESTAMP', nullable: true, description: 'Last active timestamp' },
    ],
  },

  user_branches: {
    tableName: 'user_branches',
    description: 'Pivot table linking users to one or multiple campuses for strict branch data isolation',
    primaryKey: 'id',
    foreignKeys: { user_id: 'users.id', branch_id: 'branches.id' },
    indexes: ['user_id', 'branch_id'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'Pivot UUID' },
      { name: 'user_id', type: 'VARCHAR(36)', nullable: false, description: 'Reference to users.id' },
      { name: 'branch_id', type: 'VARCHAR(36)', nullable: false, description: 'Reference to branches.id' },
      { name: 'is_primary', type: 'BOOLEAN', nullable: false, description: 'Primary branch flag' },
    ],
  },

  roles: {
    tableName: 'roles',
    description: 'Role configurations (super_admin, branch_manager, teacher, accountant, etc.)',
    primaryKey: 'id',
    foreignKeys: {},
    indexes: ['type'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'Role UUID' },
      { name: 'name', type: 'VARCHAR(64)', nullable: false, description: 'Internal role name' },
      { name: 'type', type: 'VARCHAR(32)', nullable: false, description: 'Role identifier string' },
      { name: 'description', type: 'TEXT', nullable: true, description: 'Role scope explanation' },
    ],
  },

  permissions: {
    tableName: 'permissions',
    description: 'Fine-grained permission nodes (e.g. students.create, fees.edit, reports.export)',
    primaryKey: 'id',
    foreignKeys: {},
    indexes: ['module', 'node'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'Node key' },
      { name: 'module', type: 'VARCHAR(32)', nullable: false, description: 'Module category' },
      { name: 'node', type: 'VARCHAR(64)', nullable: false, description: 'Action code' },
      { name: 'description_ar', type: 'TEXT', nullable: false, description: 'Arabic descriptor' },
      { name: 'description_en', type: 'TEXT', nullable: false, description: 'English descriptor' },
    ],
  },

  academic_years: {
    tableName: 'academic_years',
    description: 'School academic calendar years with active status, start/end dates, and atomic current year flag',
    primaryKey: 'id',
    foreignKeys: { branch_id: 'branches.id' },
    indexes: ['branch_id', 'is_current', 'status'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'Academic Year UUID' },
      { name: 'branch_id', type: 'VARCHAR(36)', nullable: false, description: 'Campus branch reference' },
      { name: 'name_ar', type: 'VARCHAR(128)', nullable: false, description: 'Arabic year title (e.g. العام الدراسي 2026-2027)' },
      { name: 'name_en', type: 'VARCHAR(128)', nullable: false, description: 'English year title (e.g. Academic Year 2026-2027)' },
      { name: 'start_date', type: 'DATE', nullable: false, description: 'Start date' },
      { name: 'end_date', type: 'DATE', nullable: false, description: 'End date' },
      { name: 'status', type: 'VARCHAR(16)', nullable: false, description: 'PLANNED | ACTIVE | CLOSED | ARCHIVED' },
      { name: 'is_current', type: 'BOOLEAN', nullable: false, description: 'Is current active academic year for branch' },
      { name: 'created_at', type: 'TIMESTAMP', nullable: false, description: 'Creation date' },
      { name: 'updated_at', type: 'TIMESTAMP', nullable: false, description: 'Update date' },
    ],
  },

  stages: {
    tableName: 'academic_stages',
    description: 'Educational stages per branch (Primary, Middle, High School)',
    primaryKey: 'id',
    foreignKeys: { branch_id: 'branches.id' },
    indexes: ['branch_id', 'display_order', 'status'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'UUID' },
      { name: 'branch_id', type: 'VARCHAR(36)', nullable: false, description: 'Associated branch' },
      { name: 'name_ar', type: 'VARCHAR(64)', nullable: false, description: 'المرحلة الابتدائية / المتوسطة / الثانوية' },
      { name: 'name_en', type: 'VARCHAR(64)', nullable: false, description: 'Primary / Middle / High School' },
      { name: 'description', type: 'TEXT', nullable: true, description: 'Stage description' },
      { name: 'display_order', type: 'INT', nullable: false, description: 'Sort sequence' },
      { name: 'status', type: 'VARCHAR(16)', nullable: false, description: 'active | inactive' },
      { name: 'created_at', type: 'TIMESTAMP', nullable: false, description: 'Creation date' },
      { name: 'updated_at', type: 'TIMESTAMP', nullable: false, description: 'Update date' },
    ],
  },

  grades: {
    tableName: 'grades',
    description: 'Grade levels within a stage (Grade 1 through Grade 12)',
    primaryKey: 'id',
    foreignKeys: { stage_id: 'stages.id', branch_id: 'branches.id' },
    indexes: ['stage_id', 'branch_id', 'grade_code', 'status'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'UUID' },
      { name: 'branch_id', type: 'VARCHAR(36)', nullable: false, description: 'Campus branch reference' },
      { name: 'stage_id', type: 'VARCHAR(36)', nullable: false, description: 'Parent stage ID' },
      { name: 'name_ar', type: 'VARCHAR(64)', nullable: false, description: 'الصف الأول / الثاني...' },
      { name: 'name_en', type: 'VARCHAR(64)', nullable: false, description: '1st Grade / 2nd Grade...' },
      { name: 'grade_code', type: 'VARCHAR(32)', nullable: false, description: 'Unique code per stage (e.g. PRI-G1)' },
      { name: 'display_order', type: 'INT', nullable: false, description: 'Sort order within stage' },
      { name: 'status', type: 'VARCHAR(16)', nullable: false, description: 'active | inactive' },
      { name: 'created_at', type: 'TIMESTAMP', nullable: false, description: 'Creation date' },
      { name: 'updated_at', type: 'TIMESTAMP', nullable: false, description: 'Update date' },
    ],
  },

  classes: {
    tableName: 'classes',
    description: 'Individual classroom sections (e.g. Grade 1-A, Grade 1-B)',
    primaryKey: 'id',
    foreignKeys: { grade_id: 'grades.id', stage_id: 'stages.id', academic_year_id: 'academic_years.id', branch_id: 'branches.id' },
    indexes: ['branch_id', 'academic_year_id', 'grade_id', 'class_code', 'status'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'UUID' },
      { name: 'branch_id', type: 'VARCHAR(36)', nullable: false, description: 'Branch' },
      { name: 'academic_year_id', type: 'VARCHAR(36)', nullable: false, description: 'Academic Year reference' },
      { name: 'stage_id', type: 'VARCHAR(36)', nullable: false, description: 'Stage reference' },
      { name: 'grade_id', type: 'VARCHAR(36)', nullable: false, description: 'Grade' },
      { name: 'name_ar', type: 'VARCHAR(64)', nullable: false, description: 'فصل 1/أ' },
      { name: 'name_en', type: 'VARCHAR(64)', nullable: false, description: 'Section 1-A' },
      { name: 'class_code', type: 'VARCHAR(32)', nullable: false, description: 'Class identifier' },
      { name: 'room_number', type: 'VARCHAR(32)', nullable: true, description: 'Room / Hall ID' },
      { name: 'capacity', type: 'INT', nullable: false, description: 'Max students' },
      { name: 'status', type: 'VARCHAR(16)', nullable: false, description: 'active | inactive' },
      { name: 'notes', type: 'TEXT', nullable: true, description: 'Section notes' },
      { name: 'created_at', type: 'TIMESTAMP', nullable: false, description: 'Creation date' },
      { name: 'updated_at', type: 'TIMESTAMP', nullable: false, description: 'Update date' },
    ],
  },

  subjects: {
    tableName: 'subjects',
    description: 'Curriculum courses and academic subjects offered per branch',
    primaryKey: 'id',
    foreignKeys: { branch_id: 'branches.id' },
    indexes: ['branch_id', 'subject_code', 'status'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'Subject UUID' },
      { name: 'branch_id', type: 'VARCHAR(36)', nullable: false, description: 'Branch reference' },
      { name: 'name_ar', type: 'VARCHAR(128)', nullable: false, description: 'Arabic subject name' },
      { name: 'name_en', type: 'VARCHAR(128)', nullable: false, description: 'English subject name' },
      { name: 'subject_code', type: 'VARCHAR(32)', nullable: false, description: 'Subject code (e.g. MATH-101)' },
      { name: 'description', type: 'TEXT', nullable: true, description: 'Syllabus summary' },
      { name: 'status', type: 'VARCHAR(16)', nullable: false, description: 'active | inactive' },
      { name: 'created_at', type: 'TIMESTAMP', nullable: false, description: 'Creation date' },
      { name: 'updated_at', type: 'TIMESTAMP', nullable: false, description: 'Update date' },
    ],
  },

  grade_subjects: {
    tableName: 'grade_subjects',
    description: 'Many-to-Many pivot linking subjects to grade levels with designated period load',
    primaryKey: 'id',
    foreignKeys: { grade_id: 'grades.id', subject_id: 'subjects.id', branch_id: 'branches.id' },
    indexes: ['branch_id', 'grade_id', 'subject_id'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'Pivot UUID' },
      { name: 'branch_id', type: 'VARCHAR(36)', nullable: false, description: 'Branch' },
      { name: 'grade_id', type: 'VARCHAR(36)', nullable: false, description: 'Grade level reference' },
      { name: 'subject_id', type: 'VARCHAR(36)', nullable: false, description: 'Subject course reference' },
      { name: 'academic_year_id', type: 'VARCHAR(36)', nullable: true, description: 'Optional Academic Year scoping' },
      { name: 'weekly_periods', type: 'INT', nullable: false, description: 'Scheduled periods per week' },
      { name: 'credit_hours', type: 'DECIMAL(4,2)', nullable: true, description: 'Credit hours' },
      { name: 'created_at', type: 'TIMESTAMP', nullable: false, description: 'Assignment date' },
    ],
  },

  students: {
    tableName: 'students',
    description: 'Core student biographical records, identification numbers, and contact profiles',
    primaryKey: 'id',
    foreignKeys: { branch_id: 'branches.id' },
    indexes: ['student_number', 'branch_id', 'status', 'national_id', 'created_at'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'Student UUID' },
      { name: 'branch_id', type: 'VARCHAR(36)', nullable: false, description: 'Campus branch foreign key' },
      { name: 'student_number', type: 'VARCHAR(32)', nullable: false, description: 'Unique school student number (e.g. STU-2026-001)' },
      { name: 'first_name_ar', type: 'VARCHAR(64)', nullable: false, description: 'First name in Arabic' },
      { name: 'last_name_ar', type: 'VARCHAR(64)', nullable: false, description: 'Family/Last name in Arabic' },
      { name: 'first_name_en', type: 'VARCHAR(64)', nullable: false, description: 'First name in English' },
      { name: 'last_name_en', type: 'VARCHAR(64)', nullable: false, description: 'Family/Last name in English' },
      { name: 'date_of_birth', type: 'DATE', nullable: false, description: 'Birth date (YYYY-MM-DD)' },
      { name: 'gender', type: 'VARCHAR(10)', nullable: false, description: 'male | female' },
      { name: 'nationality', type: 'VARCHAR(64)', nullable: false, description: 'Country of citizenship' },
      { name: 'national_id', type: 'VARCHAR(32)', nullable: true, description: 'National ID or Iqama number (protected)' },
      { name: 'passport_number', type: 'VARCHAR(32)', nullable: true, description: 'Passport number if international' },
      { name: 'phone_number', type: 'VARCHAR(32)', nullable: true, description: 'Direct contact phone' },
      { name: 'email', type: 'VARCHAR(128)', nullable: true, description: 'Personal or contact email' },
      { name: 'address', type: 'TEXT', nullable: true, description: 'Residential address' },
      { name: 'photo_url', type: 'VARCHAR(256)', nullable: true, description: 'Avatar or portrait photo URL' },
      { name: 'notes', type: 'TEXT', nullable: true, description: 'Administrative notes or medical flags' },
      { name: 'status', type: 'VARCHAR(16)', nullable: false, description: 'ACTIVE | INACTIVE | ARCHIVED' },
      { name: 'created_at', type: 'TIMESTAMP', nullable: false, description: 'Registration timestamp' },
      { name: 'updated_at', type: 'TIMESTAMP', nullable: false, description: 'Last modification timestamp' },
      { name: 'created_by', type: 'VARCHAR(36)', nullable: true, description: 'Actor user ID' },
      { name: 'updated_by', type: 'VARCHAR(36)', nullable: true, description: 'Last updater user ID' },
    ],
  },

  guardians: {
    tableName: 'guardians',
    description: 'Parents and legal guardians directory associated with students',
    primaryKey: 'id',
    foreignKeys: { branch_id: 'branches.id' },
    indexes: ['branch_id', 'phone_number', 'full_name'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'Guardian UUID' },
      { name: 'branch_id', type: 'VARCHAR(36)', nullable: false, description: 'Campus branch foreign key' },
      { name: 'full_name', type: 'VARCHAR(128)', nullable: false, description: 'Full guardian name' },
      { name: 'relationship', type: 'VARCHAR(32)', nullable: false, description: 'father | mother | brother | uncle | guardian | other' },
      { name: 'phone_number', type: 'VARCHAR(32)', nullable: false, description: 'Mobile phone number' },
      { name: 'email', type: 'VARCHAR(128)', nullable: true, description: 'Contact email' },
      { name: 'address', type: 'TEXT', nullable: true, description: 'Residence or work address' },
      { name: 'is_primary_contact', type: 'BOOLEAN', nullable: false, description: 'Primary SMS/Call recipient flag' },
      { name: 'is_emergency_contact', type: 'BOOLEAN', nullable: false, description: 'Emergency call flag' },
      { name: 'notes', type: 'TEXT', nullable: true, description: 'Special instructions or notes' },
      { name: 'created_at', type: 'TIMESTAMP', nullable: false, description: 'Creation date' },
      { name: 'updated_at', type: 'TIMESTAMP', nullable: false, description: 'Update date' },
    ],
  },

  student_guardians: {
    tableName: 'student_guardians',
    description: 'Many-to-many relationship linking students to one or more guardians',
    primaryKey: 'id',
    foreignKeys: { student_id: 'students.id', guardian_id: 'guardians.id' },
    indexes: ['student_id', 'guardian_id', 'is_primary'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'Relation UUID' },
      { name: 'student_id', type: 'VARCHAR(36)', nullable: false, description: 'Student foreign key' },
      { name: 'guardian_id', type: 'VARCHAR(36)', nullable: false, description: 'Guardian foreign key' },
      { name: 'relationship', type: 'VARCHAR(32)', nullable: false, description: 'Relationship snapshot' },
      { name: 'is_primary', type: 'BOOLEAN', nullable: false, description: 'Is primary contact for this student' },
      { name: 'is_emergency', type: 'BOOLEAN', nullable: false, description: 'Is emergency contact for this student' },
      { name: 'created_at', type: 'TIMESTAMP', nullable: false, description: 'Linking timestamp' },
    ],
  },

  enrollments: {
    tableName: 'enrollments',
    description: 'Academic enrollments placing students into year, stage, grade, and class/section',
    primaryKey: 'id',
    foreignKeys: {
      student_id: 'students.id',
      branch_id: 'branches.id',
      academic_year_id: 'academic_years.id',
      stage_id: 'stages.id',
      grade_id: 'grades.id',
      class_id: 'classes.id',
    },
    indexes: ['student_id', 'academic_year_id', 'class_id', 'status', 'branch_id'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'Enrollment UUID' },
      { name: 'student_id', type: 'VARCHAR(36)', nullable: false, description: 'Student reference' },
      { name: 'branch_id', type: 'VARCHAR(36)', nullable: false, description: 'Campus branch reference' },
      { name: 'academic_year_id', type: 'VARCHAR(36)', nullable: false, description: 'Academic year' },
      { name: 'stage_id', type: 'VARCHAR(36)', nullable: false, description: 'Academic stage' },
      { name: 'grade_id', type: 'VARCHAR(36)', nullable: false, description: 'Grade level' },
      { name: 'class_id', type: 'VARCHAR(36)', nullable: false, description: 'Class section' },
      { name: 'enrollment_date', type: 'DATE', nullable: false, description: 'Enrollment date' },
      { name: 'status', type: 'VARCHAR(16)', nullable: false, description: 'ENROLLED | PROMOTED | TRANSFERRED | SUSPENDED | WITHDRAWN | GRADUATED' },
      { name: 'previous_class_id', type: 'VARCHAR(36)', nullable: true, description: 'Previous class section if transferred' },
      { name: 'notes', type: 'TEXT', nullable: true, description: 'Enrollment remarks' },
      { name: 'created_at', type: 'TIMESTAMP', nullable: false, description: 'Creation date' },
      { name: 'updated_at', type: 'TIMESTAMP', nullable: false, description: 'Update date' },
    ],
  },

  teachers: {
    tableName: 'teachers',
    description: 'Faculty directory supporting both permanent salaried staff and hourly per-lesson instructors',
    primaryKey: 'id',
    foreignKeys: { branch_id: 'branches.id', user_id: 'users.id' },
    indexes: ['teacher_number', 'branch_id', 'employment_status', 'employment_type', 'specialization'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'Unique UUID' },
      { name: 'branch_id', type: 'VARCHAR(36)', nullable: false, description: 'Campus branch foreign key' },
      { name: 'teacher_number', type: 'VARCHAR(32)', nullable: false, description: 'Unique teacher employee code (e.g. TCH-2026-001)' },
      { name: 'first_name_ar', type: 'VARCHAR(64)', nullable: false, description: 'Arabic first name' },
      { name: 'middle_name_ar', type: 'VARCHAR(64)', nullable: true, description: 'Arabic middle name' },
      { name: 'last_name_ar', type: 'VARCHAR(64)', nullable: false, description: 'Arabic last name' },
      { name: 'first_name_en', type: 'VARCHAR(64)', nullable: false, description: 'English first name' },
      { name: 'middle_name_en', type: 'VARCHAR(64)', nullable: true, description: 'English middle name' },
      { name: 'last_name_en', type: 'VARCHAR(64)', nullable: false, description: 'English last name' },
      { name: 'full_name_ar', type: 'VARCHAR(192)', nullable: false, description: 'Computed Arabic full name' },
      { name: 'full_name_en', type: 'VARCHAR(192)', nullable: false, description: 'Computed English full name' },
      { name: 'gender', type: 'VARCHAR(16)', nullable: false, description: 'male | female' },
      { name: 'date_of_birth', type: 'DATE', nullable: true, description: 'Birthdate' },
      { name: 'nationality', type: 'VARCHAR(64)', nullable: true, description: 'Nationality name' },
      { name: 'national_id', type: 'VARCHAR(32)', nullable: true, description: 'National identity number (Protected)' },
      { name: 'passport_number', type: 'VARCHAR(32)', nullable: true, description: 'Passport number (Protected)' },
      { name: 'phone_number', type: 'VARCHAR(32)', nullable: false, description: 'Primary mobile number' },
      { name: 'alternate_phone_number', type: 'VARCHAR(32)', nullable: true, description: 'Secondary mobile number' },
      { name: 'email', type: 'VARCHAR(128)', nullable: true, description: 'Contact email' },
      { name: 'address', type: 'TEXT', nullable: true, description: 'Residential address' },
      { name: 'photo_url', type: 'TEXT', nullable: true, description: 'Profile avatar reference' },
      { name: 'hire_date', type: 'DATE', nullable: true, description: 'Appointment date' },
      { name: 'employment_status', type: 'VARCHAR(16)', nullable: false, description: 'ACTIVE | INACTIVE | ON_LEAVE | SUSPENDED | ARCHIVED' },
      { name: 'employment_type', type: 'VARCHAR(16)', nullable: false, description: 'FULL_TIME | PART_TIME | CONTRACT | TEMPORARY' },
      { name: 'specialization', type: 'VARCHAR(64)', nullable: false, description: 'Primary academic discipline' },
      { name: 'per_lesson_rate', type: 'DECIMAL(8,2)', nullable: true, description: 'Hourly wage if temporary' },
      { name: 'notes', type: 'TEXT', nullable: true, description: 'Administrative notes' },
      { name: 'user_id', type: 'VARCHAR(36)', nullable: true, description: 'Optional linked login user ID' },
      { name: 'archive_reason', type: 'TEXT', nullable: true, description: 'Reason for archiving profile' },
      { name: 'archived_at', type: 'TIMESTAMP', nullable: true, description: 'Archive timestamp' },
      { name: 'created_at', type: 'TIMESTAMP', nullable: false, description: 'Registration timestamp' },
      { name: 'updated_at', type: 'TIMESTAMP', nullable: false, description: 'Last modification timestamp' },
      { name: 'created_by', type: 'VARCHAR(36)', nullable: true, description: 'Actor user ID' },
      { name: 'updated_by', type: 'VARCHAR(36)', nullable: true, description: 'Last updater user ID' },
    ],
  },

  teacher_qualifications: {
    tableName: 'teacher_qualifications',
    description: 'Academic degrees, university diplomas, and certifications earned by teachers',
    primaryKey: 'id',
    foreignKeys: { teacher_id: 'teachers.id' },
    indexes: ['teacher_id', 'degree'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'Qualification UUID' },
      { name: 'teacher_id', type: 'VARCHAR(36)', nullable: false, description: 'Reference to teachers.id' },
      { name: 'degree', type: 'VARCHAR(64)', nullable: false, description: 'Degree title (Bachelor, Master, PhD, Diploma)' },
      { name: 'field_of_study', type: 'VARCHAR(128)', nullable: false, description: 'Specialization or major' },
      { name: 'institution', type: 'VARCHAR(128)', nullable: false, description: 'Granting university or college' },
      { name: 'graduation_year', type: 'INTEGER', nullable: false, description: 'Year of completion' },
      { name: 'is_highest_degree', type: 'BOOLEAN', nullable: false, description: 'Flag for highest degree earned' },
      { name: 'created_at', type: 'TIMESTAMP', nullable: false, description: 'Creation date' },
    ],
  },

  teacher_subjects: {
    tableName: 'teacher_subjects',
    description: 'Many-to-many relationship linking teachers to curriculum subjects they are qualified to teach',
    primaryKey: 'id',
    foreignKeys: { teacher_id: 'teachers.id', subject_id: 'subjects.id', branch_id: 'branches.id' },
    indexes: ['teacher_id', 'subject_id', 'branch_id'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'Relation UUID' },
      { name: 'teacher_id', type: 'VARCHAR(36)', nullable: false, description: 'Reference to teachers.id' },
      { name: 'subject_id', type: 'VARCHAR(36)', nullable: false, description: 'Reference to subjects.id' },
      { name: 'branch_id', type: 'VARCHAR(36)', nullable: false, description: 'Reference to branches.id' },
      { name: 'is_primary_subject', type: 'BOOLEAN', nullable: false, description: 'Primary subject flag' },
      { name: 'created_at', type: 'TIMESTAMP', nullable: false, description: 'Assignment date' },
    ],
  },

  teacher_classes: {
    tableName: 'teacher_classes',
    description: 'Class sections and homeroom/primary assignments for faculty members',
    primaryKey: 'id',
    foreignKeys: {
      teacher_id: 'teachers.id',
      class_id: 'classes.id',
      academic_year_id: 'academic_years.id',
      branch_id: 'branches.id',
    },
    indexes: ['teacher_id', 'class_id', 'academic_year_id', 'role', 'is_current'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'Association UUID' },
      { name: 'teacher_id', type: 'VARCHAR(36)', nullable: false, description: 'Teacher reference' },
      { name: 'class_id', type: 'VARCHAR(36)', nullable: false, description: 'Class section reference' },
      { name: 'academic_year_id', type: 'VARCHAR(36)', nullable: false, description: 'Academic calendar year' },
      { name: 'branch_id', type: 'VARCHAR(36)', nullable: false, description: 'Campus branch reference' },
      { name: 'role', type: 'VARCHAR(32)', nullable: false, description: 'PRIMARY_TEACHER | HOMEROOM_TEACHER | SUBJECT_TEACHER | ASSISTANT_TEACHER' },
      { name: 'is_current', type: 'BOOLEAN', nullable: false, description: 'Active assignment status flag' },
      { name: 'created_at', type: 'TIMESTAMP', nullable: false, description: 'Association timestamp' },
      { name: 'updated_at', type: 'TIMESTAMP', nullable: false, description: 'Update timestamp' },
    ],
  },

  attendance: {
    tableName: 'attendance',
    description: 'Daily roll-call records per student and class',
    primaryKey: 'id',
    foreignKeys: { student_id: 'students.id', class_id: 'classes.id', branch_id: 'branches.id' },
    indexes: ['date', 'student_id', 'class_id', 'branch_id', 'status'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'UUID' },
      { name: 'student_id', type: 'VARCHAR(36)', nullable: false, description: 'Student' },
      { name: 'class_id', type: 'VARCHAR(36)', nullable: false, description: 'Class' },
      { name: 'branch_id', type: 'VARCHAR(36)', nullable: false, description: 'Campus' },
      { name: 'date', type: 'DATE', nullable: false, description: 'Attendance date' },
      { name: 'status', type: 'VARCHAR(16)', nullable: false, description: 'present | absent | late | excused' },
      { name: 'notes', type: 'TEXT', nullable: true, description: 'Reason for absence or tardiness' },
      { name: 'recorded_by', type: 'VARCHAR(36)', nullable: false, description: 'Teacher / Staff user ID' },
    ],
  },

  audit_logs: {
    tableName: 'audit_logs',
    description: 'Security & compliance event ledger',
    primaryKey: 'id',
    foreignKeys: { user_id: 'users.id' },
    indexes: ['timestamp', 'action', 'module'],
    columns: [
      { name: 'id', type: 'VARCHAR(36)', nullable: false, description: 'UUID' },
      { name: 'user_id', type: 'VARCHAR(36)', nullable: false, description: 'Actor ID' },
      { name: 'user_name', type: 'VARCHAR(128)', nullable: false, description: 'Snapshot of actor name' },
      { name: 'action', type: 'VARCHAR(32)', nullable: false, description: 'login | logout | create | update | delete | export' },
      { name: 'module', type: 'VARCHAR(32)', nullable: false, description: 'Target module' },
      { name: 'details', type: 'TEXT', nullable: false, description: 'Context description' },
      { name: 'timestamp', type: 'TIMESTAMP', nullable: false, description: 'Action timestamp' },
    ],
  },
};
