import { PermissionDefinition, StandardPermissionKey } from '../types/auth';

export const ALL_PERMISSIONS: PermissionDefinition[] = [
  // Dashboard
  {
    key: 'dashboard.view',
    module: 'dashboard',
    nameAr: 'عرض لوحة التحكم',
    nameEn: 'View Dashboard',
    descriptionAr: 'الاطلاع على الإحصائيات والمؤشرات العامة والنشاطات الأخيرة',
    descriptionEn: 'View KPIs, high-level summaries and recent operational events',
  },
  {
    key: 'dashboard.view_finance',
    module: 'dashboard',
    nameAr: 'عرض المؤشرات المالية في لوحة التحكم',
    nameEn: 'View Dashboard Finance KPIs',
    descriptionAr: 'الاطلاع على ملخص الرسوم والتحصيلات والمستحقات في لوحة التحكم',
    descriptionEn: 'View fees, collections, and outstanding financial KPIs on dashboard',
  },
  {
    key: 'dashboard.view_cross_branch',
    module: 'dashboard',
    nameAr: 'عرض ملخص الفروع الشامل في لوحة التحكم',
    nameEn: 'View Cross-Branch Dashboard Overview',
    descriptionAr: 'مقارنة وعرض مؤشرات جميع الفروع في لوحة تحكم واحدة',
    descriptionEn: 'Compare and view statistics across all branches on dashboard',
  },
  {
    key: 'dashboard.view_activity',
    module: 'dashboard',
    nameAr: 'عرض سجل النشاطات الأخيرة في لوحة التحكم',
    nameEn: 'View Dashboard Recent Activity',
    descriptionAr: 'الاطلاع على موجز العمليات والأحداث الأخيرة في لوحة التحكم',
    descriptionEn: 'View operational audit feed and recent activity on dashboard',
  },

  // Branches Management (Phase 3)
  {
    key: 'branches.view',
    module: 'branches',
    nameAr: 'عرض الفروع المدرسية',
    nameEn: 'View Branches',
    descriptionAr: 'الاطلاع على قائمة الفروع وتفاصيلها وسعاتها الاستيعابية',
    descriptionEn: 'View campuses directory, operational parameters and details',
  },
  {
    key: 'branches.create',
    module: 'branches',
    nameAr: 'إنشاء فروع جديدة',
    nameEn: 'Create Branches',
    descriptionAr: 'إضافة وتأسيس فروع ومجمعات تعليمية جديدة في النظام',
    descriptionEn: 'Provision new school campuses and operational facilities',
  },
  {
    key: 'branches.edit',
    module: 'branches',
    nameAr: 'تعديل بيانات الفروع',
    nameEn: 'Edit Branches',
    descriptionAr: 'تحديث بيانات الفروع وعناوينها وأرقام التواصل ومدراء الفروع',
    descriptionEn: 'Update campus attributes, contacts and appointed managers',
  },
  {
    key: 'branches.delete',
    module: 'branches',
    nameAr: 'تعطيل وإدارة حالة الفروع',
    nameEn: 'Disable / Toggle Branches',
    descriptionAr: 'تعطيل أو إعادة تفعيل الفروع مع الحفاظ التام على البيانات التاريخية',
    descriptionEn: 'Deactivate or restore campuses preserving historical data records',
  },

  // Academic Structure (Phase 4)
  // Academic Years
  {
    key: 'academic_years.view',
    module: 'academic',
    nameAr: 'عرض السنوات الدراسية',
    nameEn: 'View Academic Years',
    descriptionAr: 'الاطلاع على تقويم السنوات الدراسية وفتراتها وحالاتها التشغيلية',
    descriptionEn: 'View academic calendar years, durations and status',
  },
  {
    key: 'academic_years.create',
    module: 'academic',
    nameAr: 'إنشاء سنة دراسية',
    nameEn: 'Create Academic Year',
    descriptionAr: 'تأسيس أعوام دراسية جديدة وتحديد تواريخ البداية والنهاية',
    descriptionEn: 'Set up new academic years with start and end dates',
  },
  {
    key: 'academic_years.edit',
    module: 'academic',
    nameAr: 'تعديل وتعيين السنة الحالية',
    nameEn: 'Edit & Activate Academic Year',
    descriptionAr: 'تعديل التواريخ وتعيين السنة الحالية النشطة أو إغلاقها',
    descriptionEn: 'Update dates, toggle active current year and manage status',
  },
  {
    key: 'academic_years.delete',
    module: 'academic',
    nameAr: 'أرشفة السنوات الدراسية',
    nameEn: 'Archive Academic Years',
    descriptionAr: 'أرشفة السنوات المغلقة وحفظ سجلاتها الأكاديمية التاريخية',
    descriptionEn: 'Archive closed academic years preserving historical records',
  },

  // Academic Stages
  {
    key: 'academic_stages.view',
    module: 'academic',
    nameAr: 'عرض المراحل الدراسية',
    nameEn: 'View Academic Stages',
    descriptionAr: 'الاطلاع على المراحل التعليمية (ابتدائي، متوسط، ثانوي)',
    descriptionEn: 'View educational stages (Primary, Middle, High School)',
  },
  {
    key: 'academic_stages.create',
    module: 'academic',
    nameAr: 'إنشاء مراحل دراسية',
    nameEn: 'Create Academic Stages',
    descriptionAr: 'إضافة مراحل تعليمية جديدة بالفرع',
    descriptionEn: 'Add new educational stages to the campus',
  },
  {
    key: 'academic_stages.edit',
    module: 'academic',
    nameAr: 'تعديل وترتيب المراحل',
    nameEn: 'Edit & Reorder Stages',
    descriptionAr: 'تعديل مسميات المراحل وترتيب عرضها وتحديث أوصافها',
    descriptionEn: 'Modify stage names, display sequence and descriptions',
  },
  {
    key: 'academic_stages.delete',
    module: 'academic',
    nameAr: 'تعطيل وإلغاء المراحل',
    nameEn: 'Disable / Delete Stages',
    descriptionAr: 'تعطيل المرحلة الدراسية مع حماية الصفوف التابعة لها',
    descriptionEn: 'Deactivate academic stage safeguarding attached grades',
  },

  // Grades
  {
    key: 'grades.view',
    module: 'academic',
    nameAr: 'عرض الصفوف الدراسية',
    nameEn: 'View Grades',
    descriptionAr: 'الاطلاع على قائمة الصفوف والمستويات الأكاديمية التابعة للمراحل',
    descriptionEn: 'View grade levels and academic tiers under each stage',
  },
  {
    key: 'grades.create',
    module: 'academic',
    nameAr: 'إنشاء صفوف دراسية',
    nameEn: 'Create Grades',
    descriptionAr: 'إضافة صف دراسي جديد وربطه بالمرحلة التعليمية المناسبة',
    descriptionEn: 'Create grade levels and associate with valid stages',
  },
  {
    key: 'grades.edit',
    module: 'academic',
    nameAr: 'تعديل الصفوف الدراسية',
    nameEn: 'Edit Grades',
    descriptionAr: 'تعديل مسميات الصفوف وأكوادها وترتيبها الأكاديمي',
    descriptionEn: 'Update grade names, codes and academic ordering',
  },
  {
    key: 'grades.delete',
    module: 'academic',
    nameAr: 'تعطيل الصفوف الدراسية',
    nameEn: 'Disable Grades',
    descriptionAr: 'تعطيل أو إلغاء الصفوف مع حماية الفصول والبيانات المرتبطة',
    descriptionEn: 'Deactivate grade levels with dependent class protections',
  },

  // Classes & Sections
  {
    key: 'classes.view',
    module: 'academic',
    nameAr: 'عرض الفصول الدراسية',
    nameEn: 'View Classes & Sections',
    descriptionAr: 'الاطلاع على الشُعب والفصول الدراسية وسعاتها الاستيعابية والقاعات',
    descriptionEn: 'View classroom sections, room allocations and capacities',
  },
  {
    key: 'classes.create',
    module: 'academic',
    nameAr: 'إنشاء فصول دراسية',
    nameEn: 'Create Classes & Sections',
    descriptionAr: 'إضافة شُعب وفصول جديدة ضمن الصف والسنة الدراسية المعتمدة',
    descriptionEn: 'Provision new class sections for valid grades and academic years',
  },
  {
    key: 'classes.edit',
    module: 'academic',
    nameAr: 'تعديل الفصول الدراسية',
    nameEn: 'Edit Classes & Sections',
    descriptionAr: 'تعديل مسميات الشُعب، السعات الاستيعابية، وأرقام القاعات',
    descriptionEn: 'Modify class section names, room numbers and seating capacities',
  },
  {
    key: 'classes.delete',
    module: 'academic',
    nameAr: 'تعطيل الفصول الدراسية',
    nameEn: 'Disable Classes',
    descriptionAr: 'تعطيل الشُعب أو إغلاقها مع الحفاظ على سجلاتها الأكاديمية',
    descriptionEn: 'Deactivate class sections while preserving academic archives',
  },

  // Subjects
  {
    key: 'subjects.view',
    module: 'academic',
    nameAr: 'عرض المواد الدراسية',
    nameEn: 'View Subjects',
    descriptionAr: 'الاطلاع على دليل المناهج والمواد الدراسية وأكوادها',
    descriptionEn: 'View subjects directory, curriculum codes and descriptions',
  },
  {
    key: 'subjects.create',
    module: 'academic',
    nameAr: 'إضافة مواد دراسية',
    nameEn: 'Create Subjects',
    descriptionAr: 'إضافة مواد تعليمية جديدة في النظام لكل فرع',
    descriptionEn: 'Add new academic subjects and curriculum courses per branch',
  },
  {
    key: 'subjects.edit',
    module: 'academic',
    nameAr: 'تعديل المواد الدراسية',
    nameEn: 'Edit Subjects',
    descriptionAr: 'تحديث مسميات المواد وأكوادها ووصفها الأكاديمي',
    descriptionEn: 'Update subject titles, course codes and syllabi details',
  },
  {
    key: 'subjects.delete',
    module: 'academic',
    nameAr: 'تعطيل المواد الدراسية',
    nameEn: 'Disable Subjects',
    descriptionAr: 'تعطيل المواد المنهجية مع حماية الروابط السابقة',
    descriptionEn: 'Deactivate subjects preserving historical syllabus bindings',
  },

  // Grade Subjects (Curriculum Linking)
  {
    key: 'grade_subjects.view',
    module: 'academic',
    nameAr: 'عرض خطط المناهج بالصفوف',
    nameEn: 'View Curriculum Plans',
    descriptionAr: 'الاطلاع على مصفوفة المواد المقررة لكل صف دراسي وأنصبة الحصص',
    descriptionEn: 'View curriculum matrix, subject-grade allocations and weekly quotas',
  },
  {
    key: 'grade_subjects.create',
    module: 'academic',
    nameAr: 'ربط المواد بالصفوف',
    nameEn: 'Assign Subjects to Grades',
    descriptionAr: 'تخصيص وإسناد المواد الدراسية للصفوف وتحديد عدد الحصص الأسبوعية',
    descriptionEn: 'Link courses to grades with designated weekly periods',
  },
  {
    key: 'grade_subjects.edit',
    module: 'academic',
    nameAr: 'تعديل خطة المواد بالصفوف',
    nameEn: 'Edit Grade Subjects Plan',
    descriptionAr: 'تعديل نصاب الحصص الأسبوعية للمادة أو الساعات المعتمدة للصف',
    descriptionEn: 'Update weekly period loads and credit allocations',
  },
  {
    key: 'grade_subjects.delete',
    module: 'academic',
    nameAr: 'إلغاء ربط مادة بصف',
    nameEn: 'Remove Subject from Grade',
    descriptionAr: 'فك ارتباط المادة بالصف الدراسي دون حذف المادة الأصلية',
    descriptionEn: 'Unlink subject from a grade without deleting the subject itself',
  },

  // Students
  {
    key: 'students.view',
    module: 'students',
    nameAr: 'عرض بيانات الطلاب',
    nameEn: 'View Students',
    descriptionAr: 'تصفح قائمة الطلاب، السجلات الأكاديمية وملفات أولياء الأمور',
    descriptionEn: 'Browse student rosters, academic records and parent details',
  },
  {
    key: 'students.create',
    module: 'students',
    nameAr: 'تسجيل وإضافة طلاب',
    nameEn: 'Create Students',
    descriptionAr: 'إضافة طلاب جدد وتسجيل بياناتهم وبيانات أولياء الأمور',
    descriptionEn: 'Register new students and enter guardian credentials',
  },
  {
    key: 'students.edit',
    module: 'students',
    nameAr: 'تعديل بيانات الطلاب',
    nameEn: 'Edit Students',
    descriptionAr: 'تحديث بيانات الطلاب الأكاديمية والشخصية وتعديل الصفوف',
    descriptionEn: 'Update student profiles, classroom assignments and contact info',
  },
  {
    key: 'students.delete',
    module: 'students',
    nameAr: 'حذف سجلات الطلاب',
    nameEn: 'Delete Students',
    descriptionAr: 'حذف أو أرشفة ملفات الطلاب من قاعدة البيانات',
    descriptionEn: 'Delete or archive student accounts permanently',
  },

  // Teachers
  {
    key: 'teachers.view',
    module: 'teachers',
    nameAr: 'عرض هيئة التدريس',
    nameEn: 'View Teachers',
    descriptionAr: 'الاطلاع على قائمة المعلمين الدائمين والمؤقتين وسجلات الحصص',
    descriptionEn: 'View permanent and per-lesson hourly instructors directory',
  },
  {
    key: 'teachers.create',
    module: 'teachers',
    nameAr: 'إضافة معلمين',
    nameEn: 'Create Teachers',
    descriptionAr: 'تسجيل معلمين جدد وتحديد التخصص ونوع التعاقد (دائم/مؤقت)',
    descriptionEn: 'Onboard new faculty members and contract types',
  },
  {
    key: 'teachers.edit',
    module: 'teachers',
    nameAr: 'تعديل بيانات المعلمين',
    nameEn: 'Edit Teachers',
    descriptionAr: 'تحديث تخصصات المعلمين، الأسعار للحصة، وبيانات التواصل',
    descriptionEn: 'Modify instructor rates, disciplines and contact records',
  },
  {
    key: 'teachers.delete',
    module: 'teachers',
    nameAr: 'حذف سجلات المعلمين',
    nameEn: 'Delete Teachers',
    descriptionAr: 'إلغاء أو إنهاء خدمات المعلمين من النظام',
    descriptionEn: 'Remove faculty members from the registry',
  },
  {
    key: 'teachers.archive',
    module: 'teachers',
    nameAr: 'أرشفة المعلمين',
    nameEn: 'Archive Teachers',
    descriptionAr: 'أرشفة ملفات المعلمين السابقين مع الحفاظ الكامل على سجلاتهم الأكاديمية',
    descriptionEn: 'Archive teacher accounts preserving all historical academic links',
  },
  {
    key: 'teachers.restore',
    module: 'teachers',
    nameAr: 'استعادة المعلمين المؤرشفين',
    nameEn: 'Restore Teachers',
    descriptionAr: 'استعادة ملفات المعلمين من الأرشيف وإعادتهم للخدمة النشطة',
    descriptionEn: 'Restore archived teacher profiles back to active operational status',
  },
  {
    key: 'teachers.manage_subjects',
    module: 'teachers',
    nameAr: 'إسناد المواد للمعلمين',
    nameEn: 'Manage Teacher Subjects',
    descriptionAr: 'تخصيص المواد الدراسية والمناهج التي يحق للمعلم تدريسها بالفرع',
    descriptionEn: 'Assign and manage curriculum subjects taught by the teacher',
  },
  {
    key: 'teachers.manage_classes',
    module: 'teachers',
    nameAr: 'تسكين المعلمين بالفصول',
    nameEn: 'Manage Teacher Classes',
    descriptionAr: 'إسناد الفصول والشُعب والأدوار (معلم أساسي / رائد فصل)',
    descriptionEn: 'Associate teachers with class sections and homeroom/primary roles',
  },
  {
    key: 'teachers.view_sensitive_data',
    module: 'teachers',
    nameAr: 'الاطلاع على الهوية الوطنية والمستندات',
    nameEn: 'View Sensitive Identity Data',
    descriptionAr: 'عرض أرقام الهوية الوطنية وجوازات السفر غير المقنعة للمعلمين',
    descriptionEn: 'Access unmasked national ID and passport identity records',
  },
  {
    key: 'teachers.export',
    module: 'teachers',
    nameAr: 'تصدير دليل المعلمين (CSV)',
    nameEn: 'Export Teachers Roster',
    descriptionAr: 'تصدير سجلات هيئة التدريس وبياناتهم التشغيلية إلى ملفات خارجية',
    descriptionEn: 'Export faculty rosters and contact registries to CSV interchange format',
  },

  // Timetable & Scheduling (Phase 7)
  {
    key: 'timetable.view',
    module: 'timetable',
    nameAr: 'عرض الجداول والحصص',
    nameEn: 'View Timetable & Schedules',
    descriptionAr: 'الاطلاع على الجداول الأسبوعية للفصول والمعلمين والقاعات الدراسية',
    descriptionEn: 'View weekly schedules for classes, teachers and rooms',
  },
  {
    key: 'timetable.create',
    module: 'timetable',
    nameAr: 'إنشاء وتسكين الحصص',
    nameEn: 'Create Timetable Lessons',
    descriptionAr: 'إضافة حصص جديدة للجداول وتعيين المواد والمعلمين والقاعات',
    descriptionEn: 'Schedule lessons and assign subject, teacher and room',
  },
  {
    key: 'timetable.edit',
    module: 'timetable',
    nameAr: 'تعديل ونقل الحصص',
    nameEn: 'Edit & Move Lessons',
    descriptionAr: 'تعديل تفاصيل الحصص ونقلها بين الفترات والأيام',
    descriptionEn: 'Modify lesson details and move slots across periods and days',
  },
  {
    key: 'timetable.delete',
    module: 'timetable',
    nameAr: 'حذف الحصص من الجدول',
    nameEn: 'Delete Lessons',
    descriptionAr: 'إلغاء وحذف الحصص المجدولة وإعادة الفترات إلى حالة الشغور',
    descriptionEn: 'Remove scheduled lessons and free up time slots',
  },
  {
    key: 'timetable.publish',
    module: 'timetable',
    nameAr: 'نشر واعتماد الجداول',
    nameEn: 'Publish & Lock Timetable',
    descriptionAr: 'اعتماد ونشر الجداول الدراسية بعد التحقق الآلي من خلوها من التعارضات',
    descriptionEn: 'Validate and publish weekly schedules after conflict verification',
  },
  {
    key: 'timetable.manage_periods',
    module: 'timetable',
    nameAr: 'إدارة الفترات والحصص اليومية',
    nameEn: 'Manage Periods & Bell Schedule',
    descriptionAr: 'تحديد أوقات الحصص والفسح اليومية وساعات البدء والانتهاء للفرع',
    descriptionEn: 'Configure daily bell schedule, period times and breaks per branch',
  },
  {
    key: 'timetable.manage_rooms',
    module: 'timetable',
    nameAr: 'إدارة القاعات الدراسية والمعامل',
    nameEn: 'Manage School Rooms & Labs',
    descriptionAr: 'إضافة وتعديل القاعات الدراسية والمعامل وتحديد سعاتها وأنواعها',
    descriptionEn: 'Configure classrooms, science labs and facility capacities per branch',
  },
  {
    key: 'timetable.export',
    module: 'timetable',
    nameAr: 'تصدير وطباعة الجداول',
    nameEn: 'Export & Print Timetables',
    descriptionAr: 'تصدير الجداول المعتمدة إلى صيغة CSV وتجهيزها للطباعة',
    descriptionEn: 'Export and print schedules for classes, teachers and rooms',
  },

  // Attendance
  {
    key: 'attendance.view',
    module: 'attendance',
    nameAr: 'عرض سجلات الحضور',
    nameEn: 'View Attendance',
    descriptionAr: 'الاطلاع على تقارير ونسب الحضور والغياب اليومي والشهري',
    descriptionEn: 'View daily roll call metrics and absence records',
  },
  {
    key: 'attendance.create',
    module: 'attendance',
    nameAr: 'تسجيل ورصد الحضور',
    nameEn: 'Record Attendance',
    descriptionAr: 'رصد الحضور والغياب والتأخر للطلاب والفصول يومياً',
    descriptionEn: 'Log classroom roll-calls, tardiness and absences',
  },
  {
    key: 'attendance.edit',
    module: 'attendance',
    nameAr: 'تعديل سجلات الحضور',
    nameEn: 'Edit Attendance',
    descriptionAr: 'تصحيح وتعديل حالات الغياب وإضافة الأعذار المقبولة',
    descriptionEn: 'Adjust recorded attendances and submit excused notes',
  },
  {
    key: 'attendance.delete',
    module: 'attendance',
    nameAr: 'حذف سجلات الحضور',
    nameEn: 'Delete Attendance',
    descriptionAr: 'حذف قيود الحضور الخاطئة أو الملغاة',
    descriptionEn: 'Purge invalid attendance entries',
  },
  {
    key: 'attendance.submit',
    module: 'attendance',
    nameAr: 'اعتماد وإرسال كشف الحضور',
    nameEn: 'Submit Attendance',
    descriptionAr: 'اعتماد كشف حضور الحصة أو اليوم الدراسي وإرساله للإدارة',
    descriptionEn: 'Submit and finalize attendance roster for admin review',
  },
  {
    key: 'attendance.lock',
    module: 'attendance',
    nameAr: 'قفل سجل الحضور',
    nameEn: 'Lock Attendance',
    descriptionAr: 'قفل جلسة الحضور لمنع التعديل غير المصرح به',
    descriptionEn: 'Lock attendance session against further alterations',
  },
  {
    key: 'attendance.unlock',
    module: 'attendance',
    nameAr: 'إلغاء قفل سجل الحضور',
    nameEn: 'Unlock Attendance',
    descriptionAr: 'إلغاء قفل جلسة الحضور لإتاحة المراجعة أو التعديل الاستثنائي',
    descriptionEn: 'Unlock sealed attendance session for administrative adjustments',
  },
  {
    key: 'attendance.correct',
    module: 'attendance',
    nameAr: 'تصحيح استثنائي لسجل الحضور',
    nameEn: 'Correct Attendance',
    descriptionAr: 'إجراء تصحيح رسمي وموثق لسجل الحضور بعد القفل مع تتبع التغيير',
    descriptionEn: 'Perform audited administrative corrections on attendance records',
  },
  {
    key: 'attendance.view_reports',
    module: 'attendance',
    nameAr: 'عرض تقارير الحضور والغياب',
    nameEn: 'View Attendance Reports',
    descriptionAr: 'استعراض تقارير وإحصائيات الحضور والغياب والتأخر التفصيلية',
    descriptionEn: 'Access detailed absence and punctuality analytics and reports',
  },
  {
    key: 'attendance.export',
    module: 'attendance',
    nameAr: 'تصدير سجلات وتقارير الحضور',
    nameEn: 'Export Attendance',
    descriptionAr: 'تصدير كشوف الحضور والغياب بصيغ CSV والطباعة',
    descriptionEn: 'Export attendance rosters and reports to CSV and print formats',
  },

  // Lessons
  {
    key: 'lessons.view',
    module: 'lessons',
    nameAr: 'عرض الحصص والجداول',
    nameEn: 'View Timetable & Lessons',
    descriptionAr: 'الاطلاع على مواعيد الحصص وجداول الفصول والمعلمين',
    descriptionEn: 'View weekly schedules and scheduled class periods',
  },
  {
    key: 'lessons.create',
    module: 'lessons',
    nameAr: 'إنشاء وتعيين الحصص',
    nameEn: 'Create Lessons',
    descriptionAr: 'إضافة حصص جديدة وتعيين المعلم والمادة والقاعة',
    descriptionEn: 'Schedule class sessions and allocate rooms and instructors',
  },
  {
    key: 'lessons.edit',
    module: 'lessons',
    nameAr: 'تعديل جدول الحصص',
    nameEn: 'Edit Lessons',
    descriptionAr: 'تعديل أوقات الحصص ونقل الجداول وتبديل القاعات',
    descriptionEn: 'Reschedule class sessions and shift classroom assignments',
  },
  {
    key: 'lessons.delete',
    module: 'lessons',
    nameAr: 'إلغاء وحذف الحصص',
    nameEn: 'Delete Lessons',
    descriptionAr: 'إلغاء حصص مجدولة أو مسح فترات من الجدول',
    descriptionEn: 'Cancel scheduled periods or remove curriculum slots',
  },

  // Fees
  {
    key: 'fees.view',
    module: 'fees',
    nameAr: 'عرض الرسوم والمستحقات',
    nameEn: 'View Fees',
    descriptionAr: 'الاطلاع على مستحقات الرسوم الدراسية وحالات السداد للطلاب',
    descriptionEn: 'Review tuition ledgers, balances and payment status',
  },
  {
    key: 'fees.create',
    module: 'fees',
    nameAr: 'إنشاء هياكل وفواتير الرسوم',
    nameEn: 'Create Fees & Invoices',
    descriptionAr: 'إنشاء بنود وهياكل الرسوم الدراسية وإصدار الفواتير',
    descriptionEn: 'Create fee structures, pricing items and draft invoices',
  },
  {
    key: 'fees.edit',
    module: 'fees',
    nameAr: 'تعديل الرسوم والمسودات',
    nameEn: 'Edit Fees & Drafts',
    descriptionAr: 'تعديل مبالغ الرسوم ومسودات الفواتير قبل الاعتماد',
    descriptionEn: 'Modify fee quotas, structures and draft invoices',
  },
  {
    key: 'fees.delete',
    module: 'fees',
    nameAr: 'إلغاء وحذف مسودات الرسوم',
    nameEn: 'Delete Fee Drafts',
    descriptionAr: 'حذف مسودات الرسوم غير المعتمدة أو أرشفة الهياكل',
    descriptionEn: 'Delete unissued fee drafts or archive fee structures',
  },
  {
    key: 'fees.manage_structures',
    module: 'fees',
    nameAr: 'إدارة وتعيين هياكل الرسوم',
    nameEn: 'Manage Fee Structures',
    descriptionAr: 'إضافة وتحديث وتفعيل هياكل الرسوم الدراسية حسب المراحل والصفوف',
    descriptionEn: 'Add, update and activate tuition fee structures across stages and grades',
  },
  {
    key: 'fees.assign',
    module: 'fees',
    nameAr: 'إسناد الرسوم للطلاب والفصول',
    nameEn: 'Assign Student Fees',
    descriptionAr: 'تخصيص بنود وهياكل الرسوم الدراسية للطلاب وفصول المدرسة',
    descriptionEn: 'Allocate tuition fee items to enrolled students and class sections',
  },
  {
    key: 'fees.issue',
    module: 'fees',
    nameAr: 'اعتماد وإصدار الفواتير الرسمية',
    nameEn: 'Issue Invoices',
    descriptionAr: 'إصدار الفواتير المستحقة ونقلها من حالة المسودة إلى الصادرة الرسمية',
    descriptionEn: 'Issue draft invoices into binding official financial charges',
  },
  {
    key: 'fees.void',
    module: 'fees',
    nameAr: 'إلغاء الفواتير وإبطالها (Void)',
    nameEn: 'Void Invoices',
    descriptionAr: 'إبطال وإلغاء الفواتير الصادرة غير المسددة مع توثيق السبب المعتمد',
    descriptionEn: 'Void issued unpaid invoices with documented justification',
  },
  {
    key: 'fees.apply_discount',
    module: 'fees',
    nameAr: 'تطبيق وتعديل الخصومات المالية',
    nameEn: 'Apply Fee Discounts',
    descriptionAr: 'منح خصومات مالية ثابتة أو نسبية على فواتير الطلاب',
    descriptionEn: 'Grant fixed amount or percentage discounts on student invoices',
  },
  {
    key: 'fees.apply_scholarship',
    module: 'fees',
    nameAr: 'إقرار المنح والإعفاءات الدراسية',
    nameEn: 'Apply Scholarships & Waivers',
    descriptionAr: 'اعتماد المنح الدراسية والإعفاءات الرسمية من الرسوم',
    descriptionEn: 'Authorize scholarships, bursaries and official fee waivers',
  },

  // Payments & Receipts
  {
    key: 'payments.view',
    module: 'fees',
    nameAr: 'عرض سجل المدفوعات والسندات',
    nameEn: 'View Payments & Receipts',
    descriptionAr: 'الاطلاع على حركات التحصيل وسندات القبض المالية للطلاب',
    descriptionEn: 'View payment transactions, receipt ledgers and collection history',
  },
  {
    key: 'payments.create',
    module: 'fees',
    nameAr: 'تسجيل المقبوضات وإصدار السندات',
    nameEn: 'Record Payments',
    descriptionAr: 'تسجيل دفعات سداد الرسوم النقدية والتحويلية وإصدار سندات القبض الفورية',
    descriptionEn: 'Record cash, card or bank transfer payments and issue instant receipts',
  },
  {
    key: 'payments.edit',
    module: 'fees',
    nameAr: 'تعديل بيانات المدفوعات الإدارية',
    nameEn: 'Edit Payment Notes',
    descriptionAr: 'تعديل الملاحظات أو المراجع البنكية لسندات القبض دون المساس بالمبلغ',
    descriptionEn: 'Update reference notes or transaction identifiers on payments',
  },
  {
    key: 'payments.delete',
    module: 'fees',
    nameAr: 'إبطال حركات الدفع',
    nameEn: 'Void Payments',
    descriptionAr: 'إلغاء وإبطال دفعات خاطئة وفق إجراءات تدقيق صارمة',
    descriptionEn: 'Void invalid payment entries under strict administrative controls',
  },
  {
    key: 'payments.refund',
    module: 'fees',
    nameAr: 'معالجة سندات الصرف والاسترداد',
    nameEn: 'Process Refunds',
    descriptionAr: 'إنشاء ومعالجة طلبات استرداد الرسوم المدفوعة مع ربطها بالسند الأصلي',
    descriptionEn: 'Initiate and process tuition refund vouchers tied to original payments',
  },
  {
    key: 'payments.approve_refund',
    module: 'fees',
    nameAr: 'اعتماد وموافقة سندات الاسترداد',
    nameEn: 'Approve Refunds',
    descriptionAr: 'الموافقة الإدارية العليا على عمليات الصرف واسترداد المبالغ',
    descriptionEn: 'Approve refund vouchers prior to financial disbursement',
  },
  {
    key: 'payments.export',
    module: 'fees',
    nameAr: 'تصدير وطباعة السندات والمدفوعات',
    nameEn: 'Export Payments & Receipts',
    descriptionAr: 'تصدير كشوفات المقبوضات وطباعة إيصالات السداد الرسمية',
    descriptionEn: 'Export collection sheets to CSV and print official receipts',
  },

  // Finance & Financial Reports
  {
    key: 'finance.view_reports',
    module: 'fees',
    nameAr: 'عرض التقارير والقوائم المالية',
    nameEn: 'View Financial Reports',
    descriptionAr: 'استعراض تقارير المتأخرات، كشوفات الحساب، المقبوضات اليومية والتسويات',
    descriptionEn: 'Access student statements, aging balances, daily collections and audit reports',
  },
  {
    key: 'finance.export',
    module: 'fees',
    nameAr: 'تصدير التقارير المالية',
    nameEn: 'Export Financial Reports',
    descriptionAr: 'تصدير البيانات والقوائم المالية بصيغة CSV وجداول إكسل',
    descriptionEn: 'Export financial reports and receivables ledgers to CSV format',
  },
  {
    key: 'finance.manage_settings',
    module: 'fees',
    nameAr: 'إدارة الإعدادات المالية والعملات',
    nameEn: 'Manage Finance Settings',
    descriptionAr: 'ضبط العملة الافتراضية، شروط السداد، وسياسات الرسوم',
    descriptionEn: 'Configure school currency, payment policies and terms',
  },

  // Reports
  {
    key: 'reports.view',
    module: 'reports',
    nameAr: 'عرض التقارير والإحصاءات',
    nameEn: 'View Reports',
    descriptionAr: 'الاطلاع على التقارير الشاملة للطلاب والمالية والأكاديمية',
    descriptionEn: 'Access multi-dimensional analytics and summary reports',
  },
  {
    key: 'reports.export',
    module: 'reports',
    nameAr: 'تصدير التقارير (Excel/CSV)',
    nameEn: 'Export Reports',
    descriptionAr: 'تصدير البيانات والتقارير إلى ملفات خارجية',
    descriptionEn: 'Export records to spreadsheet and data interchange formats',
  },
  {
    key: 'reports.print',
    module: 'reports',
    nameAr: 'طباعة التقارير والشهادات',
    nameEn: 'Print Reports',
    descriptionAr: 'طباعة الإيصالات، الشهادات والتقارير الرسمية',
    descriptionEn: 'Print physical invoices, certificates and audit summaries',
  },

  // Users & Security
  {
    key: 'users.view',
    module: 'users',
    nameAr: 'عرض المستخدمين',
    nameEn: 'View Users',
    descriptionAr: 'الاطلاع على حسابات موظفي النظام وأدوارهم وحالاتهم',
    descriptionEn: 'Browse staff accounts, role mappings and active statuses',
  },
  {
    key: 'users.create',
    module: 'users',
    nameAr: 'إنشاء مستخدمين جدد',
    nameEn: 'Create Users',
    descriptionAr: 'تسجيل حسابات جديدة للموظفين وتعيين كلمات المرور المبدئية',
    descriptionEn: 'Provision new staff logins and initial security credentials',
  },
  {
    key: 'users.edit',
    module: 'users',
    nameAr: 'تعديل المستخدمين والأدوار',
    nameEn: 'Edit Users',
    descriptionAr: 'تعديل الأدوار، تعطيل/تفعيل الحسابات وإعادة تعيين كلمات المرور',
    descriptionEn: 'Modify user roles, disable/enable accounts and reset credentials',
  },
  {
    key: 'users.delete',
    module: 'users',
    nameAr: 'حذف المستخدمين',
    nameEn: 'Delete Users',
    descriptionAr: 'حذف حسابات الموظفين نهائياً من النظام (مع حماية Super Admin)',
    descriptionEn: 'Permanently remove staff accounts (Super Admin protected)',
  },

  // Settings
  {
    key: 'settings.view',
    module: 'settings',
    nameAr: 'عرض إعدادات النظام',
    nameEn: 'View Settings',
    descriptionAr: 'الاطلاع على تكوينات المدرسة والسياسات العامة',
    descriptionEn: 'Review organization policies and system parameters',
  },
  {
    key: 'settings.edit',
    module: 'settings',
    nameAr: 'تعديل إعدادات النظام',
    nameEn: 'Edit Settings',
    descriptionAr: 'تعديل السياسات العامة والأمان وتكوينات الفروع',
    descriptionEn: 'Modify global school parameters and operational policies',
  },

  // AI Assistant
  {
    key: 'ai_assistant.use',
    module: 'ai',
    nameAr: 'استخدام المساعد الذكي',
    nameEn: 'Use AI Assistant',
    descriptionAr: 'الاستعلام والتشاور مع المساعد الذكي لتحليل البيانات',
    descriptionEn: 'Query school intelligence and get analytical summaries',
  },

  // Audit & Activity Center (Phase 13)
  {
    key: 'audit.view',
    module: 'audit',
    nameAr: 'عرض مركز النشاط وسجل العمليات',
    nameEn: 'View Activity & Audit Logs',
    descriptionAr: 'الاطلاع على سجل العمليات والنشاطات غير الحساسة ضمن الفرع المصرح به',
    descriptionEn: 'View operational activity logs and audit records within permitted branch',
  },
  {
    key: 'audit.view_security',
    module: 'audit',
    nameAr: 'عرض سجلات الأمان ومحاولات الاختراق',
    nameEn: 'View Security Audit Logs',
    descriptionAr: 'الاطلاع على محاولات الوصول غير المصرح، وعزل الفروع، وهجمات حقن الأوامر',
    descriptionEn: 'Inspect security denials, branch violations and prompt injection alerts',
  },
  {
    key: 'audit.view_finance',
    module: 'audit',
    nameAr: 'عرض تفاصيل العمليات المالية بالسجل',
    nameEn: 'View Financial Audit Details',
    descriptionAr: 'الاطلاع على تفاصيل المبالغ والفواتير والسندات في سجل العمليات',
    descriptionEn: 'Inspect monetary amounts and payment ledger activity records',
  },
  {
    key: 'audit.view_ai',
    module: 'audit',
    nameAr: 'عرض سجل نشاط المساعد الذكي',
    nameEn: 'View AI Assistant Activity',
    descriptionAr: 'الاطلاع على استفسارات المساعد الذكي والأدوات والإجراءات المقترحة والمنفذة',
    descriptionEn: 'Review AI queries, tool executions, proposals and confirmations',
  },
  {
    key: 'audit.export',
    module: 'audit',
    nameAr: 'تصدير وطباعة سجل العمليات',
    nameEn: 'Export & Print Audit Logs',
    descriptionAr: 'تصدير سجل العمليات المصفى إلى ملفات Excel و CSV وطباعتها',
    descriptionEn: 'Export and print filtered audit trail reports',
  },

  // Notifications (Phase 13)
  {
    key: 'notifications.view',
    module: 'notifications',
    nameAr: 'عرض واستقبال الإشعارات',
    nameEn: 'View & Receive Notifications',
    descriptionAr: 'استقبال التنبيهات وإشعارات النظام والتفاعل معها وتخصيص تفضيلاتها',
    descriptionEn: 'Receive and interact with operational school alerts and notifications',
  },
];

// Helper to group permissions by module
export const PERMISSIONS_BY_MODULE = ALL_PERMISSIONS.reduce<Record<string, PermissionDefinition[]>>(
  (acc, perm) => {
    if (!acc[perm.module]) acc[perm.module] = [];
    acc[perm.module].push(perm);
    return acc;
  },
  {}
);
