import { RoleModel, StandardPermissionKey } from '../types/auth';
import { ALL_PERMISSIONS } from './permissions';

const ALL_PERMISSION_KEYS: StandardPermissionKey[] = ALL_PERMISSIONS.map((p) => p.key);

export const DEFAULT_ROLES: RoleModel[] = [
  {
    id: 'role-super-admin',
    code: 'SUPER_ADMIN',
    nameAr: 'مدير عام النظام (Super Admin)',
    nameEn: 'Super Administrator',
    descriptionAr: 'يمتلك كامل الصلاحيات الإدارية والأمنية والتشغيلية في النظام دون أي قيود.',
    descriptionEn: 'Unrestricted master access across all administrative, security and operational modules.',
    permissions: [...ALL_PERMISSION_KEYS],
    isSystem: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'role-admin',
    code: 'ADMIN',
    nameAr: 'مدير النظام (Admin)',
    nameEn: 'Administrator',
    descriptionAr: 'إدارة معظم العمليات اليومية والمستخدمين والتقارير وإعدادات المدرسة.',
    descriptionEn: 'Manages school operations, staff accounts, reports and curriculum.',
    permissions: [
      'dashboard.view',
      'branches.view', 'branches.create', 'branches.edit',
      'academic_years.view', 'academic_years.create', 'academic_years.edit', 'academic_years.delete',
      'academic_stages.view', 'academic_stages.create', 'academic_stages.edit', 'academic_stages.delete',
      'grades.view', 'grades.create', 'grades.edit', 'grades.delete',
      'classes.view', 'classes.create', 'classes.edit', 'classes.delete',
      'subjects.view', 'subjects.create', 'subjects.edit', 'subjects.delete',
      'grade_subjects.view', 'grade_subjects.create', 'grade_subjects.edit', 'grade_subjects.delete',
      'students.view', 'students.create', 'students.edit', 'students.delete',
      'teachers.view', 'teachers.create', 'teachers.edit', 'teachers.delete', 'teachers.archive', 'teachers.restore', 'teachers.manage_subjects', 'teachers.manage_classes', 'teachers.view_sensitive_data', 'teachers.export',
      'timetable.view', 'timetable.create', 'timetable.edit', 'timetable.delete', 'timetable.publish', 'timetable.manage_periods', 'timetable.manage_rooms', 'timetable.export',
      'attendance.view', 'attendance.create', 'attendance.edit', 'attendance.delete', 'attendance.submit', 'attendance.lock', 'attendance.unlock', 'attendance.correct', 'attendance.view_reports', 'attendance.export',
      'lessons.view', 'lessons.create', 'lessons.edit',
      'fees.view', 'fees.create', 'fees.edit',
      'reports.view', 'reports.export', 'reports.print',
      'users.view', 'users.create', 'users.edit',
      'settings.view',
      'ai_assistant.use',
    ],
    isSystem: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'role-manager',
    code: 'MANAGER',
    nameAr: 'مدير شؤون تعليمية (Manager)',
    nameEn: 'School Manager',
    descriptionAr: 'إشراف على الطلاب والمعلمين والجداول وسجلات الحضور والتقارير.',
    descriptionEn: 'Oversees academic operations, student rosters, faculty, schedules and reports.',
    permissions: [
      'dashboard.view',
      'branches.view',
      'academic_years.view', 'academic_years.create', 'academic_years.edit',
      'academic_stages.view', 'academic_stages.create', 'academic_stages.edit',
      'grades.view', 'grades.create', 'grades.edit',
      'classes.view', 'classes.create', 'classes.edit',
      'subjects.view', 'subjects.create', 'subjects.edit',
      'grade_subjects.view', 'grade_subjects.create', 'grade_subjects.edit',
      'students.view', 'students.create', 'students.edit',
      'teachers.view', 'teachers.create', 'teachers.edit', 'teachers.manage_subjects', 'teachers.manage_classes', 'teachers.export',
      'timetable.view', 'timetable.create', 'timetable.edit', 'timetable.publish', 'timetable.manage_periods', 'timetable.manage_rooms', 'timetable.export',
      'attendance.view', 'attendance.create', 'attendance.edit', 'attendance.submit', 'attendance.lock', 'attendance.unlock', 'attendance.correct', 'attendance.view_reports', 'attendance.export',
      'lessons.view', 'lessons.create', 'lessons.edit',
      'fees.view',
      'reports.view', 'reports.export', 'reports.print',
      'ai_assistant.use',
    ],
    isSystem: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'role-teacher',
    code: 'TEACHER',
    nameAr: 'معلم (Teacher)',
    nameEn: 'Teacher / Faculty',
    descriptionAr: 'الاطلاع على الفصول وجداول الحصص ورصد حضور وغياب الطلاب في حصصه.',
    descriptionEn: 'Accesses assigned student rosters, timetable schedules and records roll calls.',
    permissions: [
      'dashboard.view',
      'academic_stages.view',
      'grades.view',
      'classes.view',
      'subjects.view',
      'grade_subjects.view',
      'students.view',
      'timetable.view',
      'attendance.view', 'attendance.create', 'attendance.edit', 'attendance.submit',
      'lessons.view',
      'ai_assistant.use',
    ],
    isSystem: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'role-staff',
    code: 'STAFF',
    nameAr: 'موظف استقبال ورصد (Staff)',
    nameEn: 'Operational Staff / Clerk',
    descriptionAr: 'رصد الحضور اليومي، المساعدة في تسجيل الطلاب وإصدار السندات البسيطة.',
    descriptionEn: 'Daily attendance monitoring, student intake assistance and registry tasks.',
    permissions: [
      'dashboard.view',
      'classes.view',
      'students.view', 'students.create',
      'attendance.view', 'attendance.create', 'attendance.edit', 'attendance.submit', 'attendance.view_reports',
      'fees.view', 'fees.create',
      'reports.print',
    ],
    isSystem: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'role-viewer',
    code: 'VIEWER',
    nameAr: 'مشاهد / مدقق (Viewer)',
    nameEn: 'Auditor / Viewer (Read Only)',
    descriptionAr: 'صلاحيات قراءة واطلاع فقط دون إمكانية التعديل أو الحذف.',
    descriptionEn: 'Read-only inspection rights across dashboards, rosters and ledgers.',
    permissions: [
      'dashboard.view',
      'academic_years.view',
      'academic_stages.view',
      'grades.view',
      'classes.view',
      'subjects.view',
      'grade_subjects.view',
      'students.view',
      'teachers.view',
      'timetable.view',
      'attendance.view',
      'attendance.view_reports',
      'lessons.view',
      'fees.view',
      'reports.view',
    ],
    isSystem: true,
    createdAt: '2026-01-01T00:00:00.000Z',
  },
];
